# Generated by Django 3.0.4 on 2020-04-04 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('king', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='king',
            name='picture',
        ),
    ]
